version: '3.8'

services:
  desarollador-v4:
    container_name: desarollador-contenedor-v4
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081" #¡CAMBIADO AQUÍ! (Mismo puerto adentro y afuera)
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/db_desarrolladores?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: always